add counter button and toggle logo button
fwdp-sessions/domanipulation pull request #15
Opened 2023-08-07 23:08 UTC by DenverBrian

# REQUIREMENTS

- [x] done creating 2 buttons
- [x] Button 1(Counter) - done with functionality
- [x] Button 2(Toggle Vite) -done with functionality

- [  ] Listen to events

2023-08-07 23:10 UTC, directormac requested changes
Please finish everything before we merge your pr.

2023-08-07 23:12 UTC, DenverBrian commented
> Please finish everything before we merge your pr.

noted

2023-08-07 23:20 UTC, directormac requested changes
Add functionaly within the newly created elements

2023-08-07 23:34 UTC, directormac commented on src/denver/index.ts
> +  //FIXME: change approach
Go ahead seems redundant to put an initial value of false, when the element itself is not appended yet.

2023-08-07 23:34 UTC, directormac commented on src/denver/index.ts
> +  //FIXME: change approach
@DenverBrian

2023-08-07 23:35 UTC, DenverBrian commented on src/denver/index.ts
> +  //FIXME: change approach
noted

2023-08-07 23:36 UTC, directormac requested changes
Do it now

2023-08-07 23:37 UTC, directormac commented on src/denver/index.ts
> +  //FIXME: change approach
Implement the changes ASAP

2023-08-08 18:53 UTC, boosquack commented
### Complete task requirements

- Done creating the 2 Buttons (Counter, Toggle Vite) with the functionalities needed to operate.
- Done adding the functionalities with event listeners.
- Completed  form part which includes password input and a submit button.
- Done creating another button to trigger the password type input.

2023-08-08 22:09 UTC, merged